version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "louisroyer"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "louisroyer"
  - package-ecosystem: "docker"
    directory: "/"
    scredule:
      interval: "daily"
    assignees:
      - "louisroyer"
