name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-release:
    name: Build release artifacts
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
    strategy:
      matrix:
        os: [linux]
        arch: [amd64]
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
      CGO_ENABLED: "0"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get version number
        id: version
        run: echo "version=$(echo ${{ github.ref_name }} | cut -c2- -)" >> $GITHUB_OUTPUT
      - name: Get name of repo
        id: repo
        run: echo "repo=$(echo ${{ github.repository }} | cut -d/ -f2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Install depends
        run: go get .
      - name: Build
        run: go build -v -o ${{ steps.repo.outputs.repo }}-${{ steps.version.outputs.version }}-${{ matrix.os }}-${{ matrix.arch }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: ${{ steps.repo.outputs.repo }}-*
      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ steps.repo.outputs.repo }}-${{ steps.version.outputs.version }}-${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ steps.repo.outputs.repo }}-*
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Login to docker image repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Git commit timestamps
        id: timestamp
        run: echo "timestamp=$(git log -1 --pretty=%ct)" >> $GITHUB_OUTPUT
      - name: Get Git commit timestamp in iso8601 format
        id: iso8601
        run: echo "iso8601=$(git log -n1 --pretty=%cI)" >> $GITHUB_OUTPUT
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          labels: "org.opencontainers.image.created=${{ steps.iso8601.outputs.iso8601 }}"
          images: "ghcr.io/${{ github.repository }}"
          tags: |
            type=semver,pattern={{version}}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          provenance: mode=max
          sbom: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          SOURCE_DATE_EPOCH: ${{ steps.timestamp.outputs.timestamp }}
  release:
    runs-on: ubuntu-latest
    needs: [build-release, docker-image]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get version number
        id: version
        run: echo "version=$(echo ${{ github.ref_name }} | cut -c2- -)" >> $GITHUB_OUTPUT
      - name: Get name of repo
        id: repo
        run: echo "repo=$(echo ${{ github.repository }} | cut -d/ -f2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: ${{ steps.repo.outputs.repo }}-${{ steps.version.outputs.version }}-*
          merge-multiple: true
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          makeLatest: "legacy"
          name: "Version ${{ steps.version.outputs.version }}"
          artifacts: "${{ steps.repo.outputs.repo }}-${{ steps.version.outputs.version }}-*"
          immutableCreate: true
